Repository soolsul/soolsul-server, pull requests merged in 2022-12, with the labels that each got.

#100 [Fix-#98] CustomUser Null point문제 해결
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
  src/main/java/com/soolsul/soolsulserver/user/auth/Role.java
  src/main/java/com/soolsul/soolsulserver/user/auth/filter/JwtAuthenticationFilter.java
Labels: bug

#105 [Refactor]: 테스트 샘플데이터 추가를 위한 데이터 관련 컴포넌트 이동
  src/test/java/com/soolsul/soolsulserver/acceptance/AcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/MyPageAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostStep.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoader.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoaderBootstrap.java
  src/test/java/com/soolsul/soolsulserver/data/DatabaseCleanup.java
Labels: refactor

#109 [Feat-#102] Role 계층 권한 구현
  build.gradle
  src/main/java/com/soolsul/soolsulserver/common/config/SecurityConfig.java
  src/main/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/query/ReplyQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/user/auth/business/RoleHierarchyService.java
  src/main/java/com/soolsul/soolsulserver/user/auth/business/RoleHierarchyServiceImpl.java
  src/main/java/com/soolsul/soolsulserver/user/auth/domain/RoleHierarchy.java
  src/main/java/com/soolsul/soolsulserver/user/auth/init/SecurityInitializer.java
  src/main/java/com/soolsul/soolsulserver/user/auth/listener/SetupDataLoader.java
  src/main/java/com/soolsul/soolsulserver/user/auth/persistence/RoleHierarchyRepository.java
  src/main/java/com/soolsul/soolsulserver/user/auth/persistence/UserQueryRepositoryImpl.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoader.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoaderBootstrap.java
Labels: feat

#112 feat: TestContainer를 사용한 테스트 구현 완료
  build.gradle
  src/test/java/com/soolsul/soolsulserver/acceptance/AcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/common/TestRedisContainer.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoader.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoaderBootstrap.java
  src/test/resources/logback-test.xml
Labels: database, feat

#118 [setting] Test용 application.yml파일 추가
  src/test/resources/application-aws.yml
  src/test/resources/application.yml
Labels: database, DevOps, setting

#123 [Refactor-#122] 테스트 커버리지 개선하기
  src/main/java/com/soolsul/soolsulserver/post/domain/PostView.java
  src/main/java/com/soolsul/soolsulserver/user/auth/domain/Authority.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostScrapTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostTest.java
  src/test/java/com/soolsul/soolsulserver/reply/domain/ReplyTest.java
  src/test/java/com/soolsul/soolsulserver/user/auth/domain/AuthorityTest.java
  src/test/java/com/soolsul/soolsulserver/user/auth/domain/UserInfoTest.java
Labels: refactor, test

#125 [Feat-#124] Kakao API를 통한 주소 변환 서비스 계층 구현
  build.gradle
  src/main/java/com/soolsul/soolsulserver/SoolsulServerApplication.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/AddressSearchClient.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/PlaceApiService.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/dto/KakaoAddressDocumentResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/dto/KakaoAddressResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/dto/KakaoSearchAddressResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/dto/KakaoSearchRoadAddressResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/kakao/KakaoAddressSearchClient.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/client/kakao/KakaoPlaceApiService.java
  src/main/java/com/soolsul/soolsulserver/bar/common/dto/request/AddressLookupRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/common/dto/response/AddressConvertResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/common/dto/response/AddressLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/common/dto/response/AddressResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/exception/InvalidAddressException.java
  src/main/java/com/soolsul/soolsulserver/common/config/FeignClientConfiguration.java
  src/main/java/com/soolsul/soolsulserver/common/config/client/KakaoClientAuthHeaderConfiguration.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/MyPageAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/MyPageStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyStep.java
  src/test/java/com/soolsul/soolsulserver/bar/businees/client/KakaoPlaceApiServiceTest.java
  src/test/java/com/soolsul/soolsulserver/common/ClientMocksExtension.java
  src/test/java/com/soolsul/soolsulserver/common/WireMockClientTest.java
  src/test/java/com/soolsul/soolsulserver/common/mock/KakaoPlaceMocks.java
  src/test/java/com/soolsul/soolsulserver/data/DataLoaderBootstrap.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostCommandFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostQueryFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostLikesTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostPhotosTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostScrapTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostTest.java
  src/test/java/com/soolsul/soolsulserver/reply/domain/ReplyTest.java
  src/test/java/com/soolsul/soolsulserver/reply/persistence/ReplyPersistenceTest.java
  src/test/java/com/soolsul/soolsulserver/study/DeleteTest.java
  src/test/resources/application.yml
  src/test/resources/payload/get-kakao-convert-address-response.json
  src/test/resources/payload/get-kakao-lookup-address-response.json
Labels: feat

#130 [Feat-#127] 문서화 완성과 Post 삭제기능 추가 구현 완료
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/mypage/mypage.adoc
  src/docs/asciidoc/post/post.adoc
  src/docs/asciidoc/reply/reply.adoc
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostCommandService.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Post.java
  src/main/java/com/soolsul/soolsulserver/post/exception/InvalidPostOwnerException.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostCommandFacade.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostCommandFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostFacadeGateway.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/main/java/com/soolsul/soolsulserver/reply/business/ReplyCommandService.java
  src/main/java/com/soolsul/soolsulserver/reply/common/dto/request/ReplyCreateRequest.java
  src/main/java/com/soolsul/soolsulserver/reply/common/dto/request/ReplyModifyRequest.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/Reply.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/ReplyContent.java
  src/main/java/com/soolsul/soolsulserver/reply/exception/ReplyNotFoundException.java
  src/main/java/com/soolsul/soolsulserver/reply/exception/handler/ReplyExceptionHandler.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyCommandFacade.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyCommandFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyFacadeGateway.java
  src/main/java/com/soolsul/soolsulserver/reply/presentation/ReplyController.java
  src/test/java/com/soolsul/soolsulserver/acceptance/CommonStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyStep.java
  src/test/java/com/soolsul/soolsulserver/documentation/Constants.java
  src/test/java/com/soolsul/soolsulserver/documentation/Documentation.java
  src/test/java/com/soolsul/soolsulserver/documentation/MypageDocumentation.java
  src/test/java/com/soolsul/soolsulserver/documentation/PostDocumentation.java
  src/test/java/com/soolsul/soolsulserver/documentation/ReplyDocumentation.java
Labels: documentation, feat
