Repository soolsul/soolsul-server, pull requests merged in 2022-11, with the labels that each got.

#9 [refactor] 도메인 패키지 디렉토리 구조 변경
  src/main/java/com/soolsul/soolsulserver/domain/common/BaseTimeEntity.java
  src/main/java/com/soolsul/soolsulserver/domain/curation/Curation.java
  src/main/java/com/soolsul/soolsulserver/domain/curation/CurationPicture.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/Alcohol.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/AlcoholCategory.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/AlcoholMenu.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/Snack.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/SnackCategory.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/SnackMenu.java
  src/main/java/com/soolsul/soolsulserver/domain/region/Location.java
  src/main/java/com/soolsul/soolsulserver/domain/region/Region.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/Restaurant.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantBookmark.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantOpenTime.java
Labels: refactor

#7 [Feat] 엔티티 작성
  src/main/java/com/soolsul/soolsulserver/config/JpaAuditingConfiguration.java
  src/main/java/com/soolsul/soolsulserver/domain/auth/Authority.java
  src/main/java/com/soolsul/soolsulserver/domain/auth/RefreshToken.java
  src/main/java/com/soolsul/soolsulserver/domain/auth/Role.java
  src/main/java/com/soolsul/soolsulserver/domain/auth/User.java
  src/main/java/com/soolsul/soolsulserver/domain/auth/UserAuthority.java
  src/main/java/com/soolsul/soolsulserver/domain/common/BaseEntity.java
  src/main/java/com/soolsul/soolsulserver/domain/common/BaseTimeEntity.java
  src/main/java/com/soolsul/soolsulserver/domain/common/Category.java
  src/main/java/com/soolsul/soolsulserver/domain/common/Duration.java
  src/main/java/com/soolsul/soolsulserver/domain/common/OwnerEntity.java
  src/main/java/com/soolsul/soolsulserver/domain/curation/Curation.java
  src/main/java/com/soolsul/soolsulserver/domain/curation/CurationPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/Alcohol.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/AlcoholCategory.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/AlcoholMenu.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/AlcoholPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/Snack.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/SnackCategory.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/SnackMenu.java
  src/main/java/com/soolsul/soolsulserver/domain/menu/SnackPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/post/Post.java
  src/main/java/com/soolsul/soolsulserver/domain/post/PostLike.java
  src/main/java/com/soolsul/soolsulserver/domain/post/PostLikeContent.java
  src/main/java/com/soolsul/soolsulserver/domain/post/PostPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/post/PostScrap.java
  src/main/java/com/soolsul/soolsulserver/domain/post/PostView.java
  src/main/java/com/soolsul/soolsulserver/domain/region/Location.java
  src/main/java/com/soolsul/soolsulserver/domain/region/Region.java
  src/main/java/com/soolsul/soolsulserver/domain/reply/Reply.java
  src/main/java/com/soolsul/soolsulserver/domain/reply/ReplyPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/Restaurant.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantBookmark.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantCategory.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantOpenTime.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/RestaurantPhoto.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/restaurantAlcoholTag.java
  src/main/java/com/soolsul/soolsulserver/domain/restaurant/restaurantMoodTag.java
  src/main/resources/application.yml
Labels: Entity

#11 [Setting] SpringSecurity Rest설정 완료
  .gitignore
  build.gradle
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
Labels: setting, spring security

#18 [feat] DatabaseCleanup 을 통한 테스트간 격리 구현
  build.gradle
  src/test/java/com/soolsul/soolsulserver/acceptance/AcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/utils/DatabaseCleanup.java
Labels: database, setting

#23 [Feat] 이미지 파일 업로드 기능 구현
  build.gradle
  src/main/java/com/soolsul/soolsulserver/images/AwsS3Config.java
  src/main/java/com/soolsul/soolsulserver/images/AwsS3ImageHandler.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
  src/test/java/com/soolsul/soolsulserver/images/LocalStackS3Config.java
  src/test/java/com/soolsul/soolsulserver/images/S3ImageHandlerTest.java
  src/test/resources/application.yml
Labels: AWS

#33 [Feat-#32] 단건 피드 조회 로직 일부 구현 완료
  build.gradle
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/post/business/CommandService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostServiceGateway.java
  src/main/java/com/soolsul/soolsulserver/post/business/QueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostDetailLikeResponse.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostDetailUserResponse.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/ReviewDetailStoreResponse.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Likes.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Post.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostLike.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostLikeContent.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostPhoto.java
  src/main/java/com/soolsul/soolsulserver/post/exception/PostNotFoundException.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostQueryController.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostResponse.java
  src/main/resources/application.yml
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/images/S3ImageHandlerTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryServiceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/domain/PostLikesTest.java
Labels: feat

#36 [Feat-#35] 바 목록 조회 로직 추가
  src/main/java/com/soolsul/soolsulserver/bar/businees/BarAlcoholTagService.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/BarMoodTagService.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/BarQueryService.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarLookupServiceConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/Bar.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarAlcoholTag.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarMoodTag.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/MoodTag.java
  src/main/java/com/soolsul/soolsulserver/bar/exception/BarNotFoundException.java
  src/main/java/com/soolsul/soolsulserver/bar/facade/BarQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarAlcoholTagQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarMoodTagRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/OrderByNull.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/BarQueryController.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/BarLookupConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/BarsLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/common/domain/Category.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/Alcohol.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholCategory.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholMenu.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholPhoto.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/persistence/AlcoholCategoryRepository.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/service/AlcoholCategoryService.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/Snack.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackCategory.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackMenu.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackPhoto.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostCommandService.java
  src/main/java/com/soolsul/soolsulserver/region/domain/Location.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarAlcoholTagQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarMoodTagRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/menu/persistence/AlcoholCategoryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostCommandServiceTest.java
Labels: feat

#41 [Feat-#34] Post List 조회 구현
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/common/userlocation/UserLocation.java
  src/main/java/com/soolsul/soolsulserver/common/userlocation/UserLocationBasedSquareRange.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostServiceGateway.java
  src/main/java/com/soolsul/soolsulserver/post/business/QueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostDetailStoreResponse.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostDetailUserResponse.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostRepository.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostCommandController.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostQueryController.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostListResponse.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/UserLocationRequest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryServiceTest.java
Labels: feat

#44 [Feat-#37] 로그인 구현완료
  build.gradle
  src/main/java/com/soolsul/soolsulserver/auth/Authority.java
  src/main/java/com/soolsul/soolsulserver/auth/CustomUser.java
  src/main/java/com/soolsul/soolsulserver/auth/RefreshToken.java
  src/main/java/com/soolsul/soolsulserver/auth/Role.java
  src/main/java/com/soolsul/soolsulserver/auth/User.java
  src/main/java/com/soolsul/soolsulserver/auth/UserAuthority.java
  src/main/java/com/soolsul/soolsulserver/auth/UserContext.java
  src/main/java/com/soolsul/soolsulserver/auth/UserInfo.java
  src/main/java/com/soolsul/soolsulserver/auth/business/CustomUserDetailsService.java
  src/main/java/com/soolsul/soolsulserver/auth/common/JwtAuthenticationEntryPoint.java
  src/main/java/com/soolsul/soolsulserver/auth/filter/FirstLoginAuthenticationFilter.java
  src/main/java/com/soolsul/soolsulserver/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/soolsul/soolsulserver/auth/filter/dto/UserDto.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationFailureHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationSuccessHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/JwtDeniedHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/jwt/JwtToken.java
  src/main/java/com/soolsul/soolsulserver/auth/jwt/JwtTokenFactory.java
  src/main/java/com/soolsul/soolsulserver/auth/jwt/TokenFactorySpec.java
  src/main/java/com/soolsul/soolsulserver/auth/presentation/AuthController.java
  src/main/java/com/soolsul/soolsulserver/auth/presentation/dto/RegisterRequest.java
  src/main/java/com/soolsul/soolsulserver/auth/provider/FirstLoginAuthenticationProvider.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/UserInfoRepository.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/UserQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/UserQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/UserRepository.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/dto/UserLookUpResponse.java
  src/main/java/com/soolsul/soolsulserver/auth/token/FirstLoginAuthenticationToken.java
  src/main/java/com/soolsul/soolsulserver/auth/token/JwtAuthenticationToken.java
  src/main/java/com/soolsul/soolsulserver/auth/util/AuthorizationExtractor.java
  src/main/java/com/soolsul/soolsulserver/auth/util/AuthorizationType.java
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/domain/OwnerEntity.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Post.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostPhoto.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostScrap.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostView.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/images/S3ImageHandlerTest.java
  src/test/java/com/soolsul/soolsulserver/study/DeleteTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostCommandServiceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryServiceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/domain/PostLikesTest.java
Labels: feat

#60 [Feat #58] 1차 서버 배포용 코드 작성
  build.gradle
  src/main/java/com/soolsul/soolsulserver/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationFailureHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationSuccessHandler.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarLookupServiceConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/FilteredBarLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/facade/BarQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/BarQueryController.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/BarLookupConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/FilteredBarsLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/common/userlocation/UserLocation.java
  src/main/java/com/soolsul/soolsulserver/common/userlocation/UserLocationBasedSquareRange.java
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostCommandService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostServiceGateway.java
  src/main/java/com/soolsul/soolsulserver/post/business/QueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostDetailStoreResponse.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostScrap.java
  src/main/java/com/soolsul/soolsulserver/post/domain/dto/FilteredPostLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostCreateRequest.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/UserLocationRequest.java
  src/main/resources/sql/data.sql
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostStep.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryServiceTest.java
Labels: feat

#54 [refactor-#53] 중심 경위도 + 레벨을 통한 경위도 범위 계산 로직 추가
  src/main/java/com/soolsul/soolsulserver/location/constants/LocationRangeConstants.java
  src/main/java/com/soolsul/soolsulserver/location/domain/LocationMagnificationLevel.java
  src/main/java/com/soolsul/soolsulserver/location/persistence/LocationMagnificationLevelRepository.java
  src/main/java/com/soolsul/soolsulserver/location/request/LocationSquareRangeRequest.java
  src/main/java/com/soolsul/soolsulserver/location/response/LocationSquareRangeCondition.java
  src/main/java/com/soolsul/soolsulserver/location/service/LocationRangeService.java
Labels: refactor

#68 [refactor-#61] 경위도 변경 리팩토링
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarLookupServiceConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/MoodTag.java
  src/main/java/com/soolsul/soolsulserver/bar/facade/BarQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarMoodTagRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/BarQueryController.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/BarLookupConditionRequest.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/FilteredBarsLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/userlocation/UserLocationBasedSquareRange.java
  src/main/java/com/soolsul/soolsulserver/location/domain/LocationMagnificationLevel.java
  src/main/java/com/soolsul/soolsulserver/location/persistence/LocationMagnificationLevelRepository.java
  src/main/java/com/soolsul/soolsulserver/location/persistence/LocationMagnificationLevelRepositoryDsl.java
  src/main/java/com/soolsul/soolsulserver/location/request/LocationSquareRangeRequest.java
  src/main/java/com/soolsul/soolsulserver/location/response/LocationSquareRangeCondition.java
  src/main/java/com/soolsul/soolsulserver/location/service/LocationRangeService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostServiceGateway.java
  src/main/java/com/soolsul/soolsulserver/post/business/QueryService.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarMoodTagRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/location/service/LocationRangeServiceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostCommandServiceTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryServiceTest.java
Labels: refactor

#69 [Feat-#62] docker-compose 추가 및 application.yml 제거
  .gitignore
  docker/docker-compose.yml
  docker/run.sh
  docker/stop.sh
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: setting

#72 [Feat-#71] BaseTimeEntity, BaseEntity 제거
  src/main/java/com/soolsul/soolsulserver/bar/domain/Bar.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarAlcoholTag.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarBookmark.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarCategory.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarMoodTag.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarOpenTime.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarPhoto.java
  src/main/java/com/soolsul/soolsulserver/common/domain/BaseEntity.java
  src/main/java/com/soolsul/soolsulserver/common/domain/BaseTimeEntity.java
  src/main/java/com/soolsul/soolsulserver/common/domain/Category.java
  src/main/java/com/soolsul/soolsulserver/curation/domain/Curation.java
  src/main/java/com/soolsul/soolsulserver/curation/domain/CurationPhoto.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/Alcohol.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholCategory.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholMenu.java
  src/main/java/com/soolsul/soolsulserver/menu/alcohol/domain/AlcoholPhoto.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/Snack.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackCategory.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackMenu.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackPhoto.java
  src/main/java/com/soolsul/soolsulserver/region/domain/Region.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/Reply.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/ReplyPhoto.java
Labels: refactor

#75 [Feat-#39] 큐레이션 목록 조회
  src/main/java/com/soolsul/soolsulserver/common/response/BaseResponse.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/curation/business/CurationQueryService.java
  src/main/java/com/soolsul/soolsulserver/curation/domain/Curation.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationsLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/facade/CurationQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/curation/persistence/CurationQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/curation/presentation/CurationQueryController.java
  src/test/java/com/soolsul/soolsulserver/curation/business/CurationQueryServiceTest.java
  src/test/java/com/soolsul/soolsulserver/curation/persistence/CurationQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/curation/presentation/CurationQueryControllerTest.java
Labels: feat

#74 [Feat-#67] 로그아웃 구현과 부분 기능 수정
  build.gradle
  src/main/java/com/soolsul/soolsulserver/auth/CustomUser.java
  src/main/java/com/soolsul/soolsulserver/auth/UserInfo.java
  src/main/java/com/soolsul/soolsulserver/auth/common/JwtAuthenticationEntryPoint.java
  src/main/java/com/soolsul/soolsulserver/auth/exception/UserUnauthorizedException.java
  src/main/java/com/soolsul/soolsulserver/auth/filter/FirstLoginAuthenticationFilter.java
  src/main/java/com/soolsul/soolsulserver/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationFailureHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/FirstLoginAuthenticationSuccessHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/JwtLogoutHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/handler/JwtLogoutSuccessHandler.java
  src/main/java/com/soolsul/soolsulserver/auth/jwt/JwtTokenFactory.java
  src/main/java/com/soolsul/soolsulserver/auth/jwt/TokenFactorySpec.java
  src/main/java/com/soolsul/soolsulserver/auth/presentation/dto/RegisterRequest.java
  src/main/java/com/soolsul/soolsulserver/auth/redis/RedisService.java
  src/main/java/com/soolsul/soolsulserver/auth/repository/UserQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/config/RedisConfig.java
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostCommandService.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/PostLookupRequest.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Post.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostPhoto.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostScrap.java
  src/main/java/com/soolsul/soolsulserver/post/domain/PostView.java
  src/main/java/com/soolsul/soolsulserver/post/facade/CommandFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostCommandFacade.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostFacadeGateway.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/post/facade/QueryFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostCommandFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/unit/post/business/PostQueryFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/utils/DatabaseCleanup.java
Labels: feat

#85 [refactor-#84] Authentication 제거 리팩토링
  src/main/java/com/soolsul/soolsulserver/post/presentation/PostController.java
  src/main/java/com/soolsul/soolsulserver/user/auth/CurrentUser.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/presentation/MyPageController.java
Labels: refactor

#86 [Feat-#82] 피드 댓글 생성과 조회
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/request/PostLookupRequest.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/response/PostDetailLikeResponse.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/response/PostDetailStoreResponse.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/response/PostDetailUserResponse.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/reply/business/ReplyCommandService.java
  src/main/java/com/soolsul/soolsulserver/reply/business/ReplyQueryService.java
  src/main/java/com/soolsul/soolsulserver/reply/business/dto/response/ReplyDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/Reply.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/ReplyContent.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/ReplyPhoto.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/ReplyRepository.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/query/ReplyQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/query/ReplyQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/reply/exception/InvalidReplyContentException.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyCommandFacade.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyCommandFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyFacadeGateway.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/reply/facade/ReplyQueryFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/reply/presentation/ReplyController.java
  src/main/java/com/soolsul/soolsulserver/reply/presentation/dto/request/PostReplyRequest.java
  src/main/java/com/soolsul/soolsulserver/reply/presentation/dto/response/PostRepliesResponse.java
  src/main/java/com/soolsul/soolsulserver/user/auth/filter/FirstLoginAuthenticationFilter.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/PostStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyStep.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostCommandFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostQueryFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostLikesTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/PostPhotosTest.java
  src/test/java/com/soolsul/soolsulserver/reply/persistence/ReplyPersistenceTest.java
Labels: feat

#83 [refactor-#17] aws image upload 기능 리팩토링
  src/main/java/com/soolsul/soolsulserver/images/component/AwsS3ImageUploader.java
  src/main/java/com/soolsul/soolsulserver/images/component/ImageMultipartFileNameGenerator.java
  src/main/java/com/soolsul/soolsulserver/images/config/AwsS3Config.java
  src/main/java/com/soolsul/soolsulserver/images/exception/ImageCategoryNotFoundException.java
  src/main/java/com/soolsul/soolsulserver/images/exception/ImageUploadFailException.java
  src/main/java/com/soolsul/soolsulserver/images/exception/InvalidImageExtensionException.java
  src/main/java/com/soolsul/soolsulserver/images/vo/ImageCategory.java
  src/main/java/com/soolsul/soolsulserver/images/vo/ImageExtension.java
  src/test/java/com/soolsul/soolsulserver/images/ImageMultipartFileNameGeneratorTest.java
  src/test/java/com/soolsul/soolsulserver/images/S3ImageUploaderTest.java
Labels: refactor

#89 [Feat-#88] 중복 회원 가입 방지와 회원 탈퇴
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/user/auth/CustomUser.java
  src/main/java/com/soolsul/soolsulserver/user/auth/UserInfo.java
  src/main/java/com/soolsul/soolsulserver/user/auth/business/CustomUserDetailsService.java
  src/main/java/com/soolsul/soolsulserver/user/auth/exception/UserAlreadyExistsException.java
  src/main/java/com/soolsul/soolsulserver/user/auth/exception/UserNicknameDuplicatedException.java
  src/main/java/com/soolsul/soolsulserver/user/auth/exception/handler/UserExceptionHandler.java
  src/main/java/com/soolsul/soolsulserver/user/auth/presentation/AuthController.java
  src/main/java/com/soolsul/soolsulserver/user/auth/presentation/dto/UserRegisterRequest.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/UserInfoRepository.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/UserRepository.java
  src/main/resources/sql/data.sql
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AuthStep.java
  src/test/java/com/soolsul/soolsulserver/reply/persistence/ReplyPersistenceTest.java
Labels: feat

#91 feat: springdocs(swagger) api 문서 추가
  build.gradle
  src/main/java/com/soolsul/soolsulserver/config/OpenApiConfig.java
  src/main/java/com/soolsul/soolsulserver/config/SecurityConfig.java
Labels: feat

#94 [Feat-#87] 사용자 정보 수정 구현 완료
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/business/dto/request/PostLookupRequest.java
  src/main/java/com/soolsul/soolsulserver/post/domain/Post.java
  src/main/java/com/soolsul/soolsulserver/post/domain/dto/UserPostLookUpResponse.java
  src/main/java/com/soolsul/soolsulserver/post/domain/dto/UserReplyLookUpResponse.java
  src/main/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/post/facade/PostQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/post/presentation/dto/PostDetailResponse.java
  src/main/java/com/soolsul/soolsulserver/reply/business/ReplyQueryService.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/query/ReplyQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/reply/domain/query/ReplyQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/user/auth/CustomUser.java
  src/main/java/com/soolsul/soolsulserver/user/auth/UserInfo.java
  src/main/java/com/soolsul/soolsulserver/user/auth/business/CustomUserDetailsService.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/UserInfoRepository.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/UserQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/UserQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/dto/response/UserEditFormResponse.java
  src/main/java/com/soolsul/soolsulserver/user/auth/repository/dto/response/UserLookUpResponse.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/facade/MyPageCommandFacade.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/facade/MyPageCommandFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/facade/MyPageQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/facade/MyPageQueryFacadeSpec.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/presentation/MyPageController.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/presentation/dto/reqeust/UserInfoEditRequest.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/presentation/dto/response/UserPostListLookUpResponse.java
  src/main/java/com/soolsul/soolsulserver/user/mypage/presentation/dto/response/UserReplyListLookUpResponse.java
  src/test/java/com/soolsul/soolsulserver/acceptance/AcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/MyPageAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/MyPageStep.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyAcceptanceTest.java
  src/test/java/com/soolsul/soolsulserver/acceptance/ReplyStep.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostQueryFacadeSpecTest.java
Labels: feat

#97 [Feat #93] 큐레이션 상세 조회 기능 추가
  src/main/java/com/soolsul/soolsulserver/bar/businees/BarSnackMenuService.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarSnackMenuResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/businees/dto/BarStreetNameAddressResponse.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/Address.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/Bar.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/BarOpenTime.java
  src/main/java/com/soolsul/soolsulserver/bar/domain/StreetNameAddress.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/persistence/BarSnackMenuRepository.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/BarQueryController.java
  src/main/java/com/soolsul/soolsulserver/bar/presentation/dto/BarLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/common/data/DataLoader.java
  src/main/java/com/soolsul/soolsulserver/common/domain/OpeningHours.java
  src/main/java/com/soolsul/soolsulserver/common/response/ResponseCodeAndMessages.java
  src/main/java/com/soolsul/soolsulserver/curation/business/CurationQueryService.java
  src/main/java/com/soolsul/soolsulserver/curation/domain/Curation.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/BarOpeningHoursResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationDetailLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationListLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationPostLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/CurationsLookupResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/dto/PostPhotoImageResponse.java
  src/main/java/com/soolsul/soolsulserver/curation/exception/CurationNotFoundException.java
  src/main/java/com/soolsul/soolsulserver/curation/facade/CurationQueryFacade.java
  src/main/java/com/soolsul/soolsulserver/curation/persistence/CurationQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/curation/presentation/CurationQueryController.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/Snack.java
  src/main/java/com/soolsul/soolsulserver/menu/snack/domain/SnackMenu.java
  src/main/java/com/soolsul/soolsulserver/post/business/PostQueryService.java
  src/main/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepository.java
  src/main/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepositoryImpl.java
  src/main/java/com/soolsul/soolsulserver/user/auth/UserInfo.java
  src/main/resources/sql/data.sql
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarAlcoholTagQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarMoodTagRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/bar/persistence/BarSnackMenuRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/curation/business/CurationQueryServiceTest.java
  src/test/java/com/soolsul/soolsulserver/curation/persistence/CurationQueryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/curation/presentation/CurationQueryControllerTest.java
  src/test/java/com/soolsul/soolsulserver/menu/persistence/AlcoholCategoryRepositoryTest.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostCommandFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/business/PostQueryFacadeSpecTest.java
  src/test/java/com/soolsul/soolsulserver/post/domain/query/PostQueryRepositoryImplTest.java
  src/test/java/com/soolsul/soolsulserver/reply/persistence/ReplyPersistenceTest.java
  src/test/java/com/soolsul/soolsulserver/study/DeleteTest.java
Labels: feat
